version: '3'
services:
  vertica:
    build: vertica
    environment:
      - VERTICA_USER=${vertica_user}
      - VERTICA_PASSWORD=${vertica_password}

  test:
    build: .
    environment:
      - VERTICA_USER=${vertica_user}
      - VERTICA_PASSWORD=${vertica_password}
    volumes:
      - .:/project/
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /project
    depends_on:
      - vertica
    command: ["-r", "/project/tests/features", "/project/tests/features"]