version: '3'
services:
  vertica:
    image: dataplatform/docker-vertica
    volumes:
      - ./data/db/vertica_data:/home/dbadmin/docker

  test:
    build: .
    volumes:
      - .:/project/
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /project
    depends_on:
      - vertica
    command: ["-r", "/project/tests/features", "/project/tests/features"]